"""empty message

Revision ID: 4125673ad4a4
Revises: b4ea2ac02274
Create Date: 2019-03-16 22:15:30.416094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4125673ad4a4'
down_revision = 'b4ea2ac02274'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_users_username'), 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_username'), 'users', type_='unique')
    # ### end Alembic commands ###
